### ISSUE TITLE
[Bug]: Incompatibility with Tubes Reloaded ? (voided items)

### ISSUE THREAD

**Issue by Dam-Buty** [cech12/WoodenHopper#17]
### Minecraft Version

1.20.1

### Forge Version

47.1.43

### Mod Version

1.20.1-1.6.0.0

### Modpack or other Mod

Private modpack with Wooden Hopper + [Tubes Reloaded](https://www.curseforge.com/minecraft/mc-mods/tubes-reloaded)

### Describe the Issue

If i place a tube (with no inventory attached to it) with a wooden hopper pointing into it, then put items inside the wooden hopper, the items will start getting pulled but are just voided by the tube.

The bug doesn't occur with normal hoppers. Not sure if it comes from this mod or the other so i'll crosspost the issue.

![2023-08-14_21 44 21](https://github.com/cech12/WoodenHopper/assets/1461760/ec7b8dc1-91cf-4854-9c21-e74a0c3d721c)

### Logs

none

### Do you use any performance-enhancing mods (e.g. OptiFine)?

nope

**Comment by Dam-Buty** [comment]
https://github.com/Commoble/tubesreloaded/issues/24

**Comment by cech12** [comment]
Thanks for your report! A fix will be released in the upcoming versions 1.19.4-1.4.0.1 and 1.20.1-1.6.0.1

**Comment by Dam-Buty** [comment]
> Thanks for your report! A fix will be released in the upcoming versions 1.19.4-1.4.0.1 and 1.20.1-1.6.0.1

Wow that was really quick ! Thanks for the fix :fire:

**Comment by Dam-Buty** [comment]
Confirmed working with Tubes Reloaded latest version (3.1.0) :+1:

**Comment by cech12** [comment]
Thanks for your feedback! Nice to hear that! :)
