### ISSUE TITLE
[Bug]: Neoforge 21.0.82 changes crash on launch

### ISSUE THREAD

**Issue by ffuentesm** [cech12/WoodenHopper#26]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

21.0.86

### Mod Version

woodenhopper-neoforge-1.21-3.0.0.0

### Describe the Issue

![image](https://github.com/user-attachments/assets/6eccda86-a317-4a1f-a205-d6fd905711af)

### Logs

https://pastebin.com/Krbji737

**Comment by cech12** [comment]
Thanks for your report! Downgrading Neoforge to 21.0.81 could be a workaround for now until I fix that issue :)

**Comment by cech12** [comment]
Thanks again for your report! The crash is fixed in the upcoming version 1.21-3.1.0.0.

**Comment by cech12** [comment]
https://github.com/cech12/WoodenHopper/commit/22fe5f3ae146491fcc078820ae858fe58df88fe4
