### ISSUE TITLE
Feature Request - Add config to deactivate the hopper's suction

### ISSUE THREAD

**Issue by martiesim** [cech12/WoodenHopper#3]
Hello,
I know this request might not be completely in line with what you originally planned this mod for but I hoped this would be doable with a reasonable amount of work.
Could you maybe add a config option to deactivate the hopper's suction of items form the world or inventories?
This way I could use this mod in a similar way to the Ducts mod for fabric.
A version compatible with forge 1.16.3 would be a dream :)

I'm sadly not able to do this myself, as I have no idea how mods actually work. I am, however, able to read java code a little so took a dive in your repository and I think you would only need to deactivate the pullItems method in the WoodenHopperTileEntity class.
https://github.com/cech12/WoodenHopper/blob/75eee23d8c53256fbfd16028326c52095e66b38b/src/main/java/cech12/woodenhopper/tileentity/WoodenHopperTileEntity.java#L288

Thank you for considering it :)

**Comment by cech12** [comment]
The mod is compatible with Forge 1.16.3! ;)

I like this feature request. Thanks for that! I will look into this when I have some time. :)

**Comment by martiesim** [comment]
Thank you very much for looking into this.

When I mentioned 1.16.3 I was referring to my feature request. Some mod authors only add new stuff to their newest version (which is a valid strategy) but my whole installation currently runs 1.16.3 and I can't update at the moment because of some mods. So if you could add this feature to the 1.16.3 compatible version, that would be really cool :)

**Comment by cech12** [comment]
Ahhh, I understand what you mean^^ I try to support older versions as long as possible. :) Only when Forge made breaking changes, I update the supported version :) So, your feature request should not cause a version update :)

**Comment by cech12** [comment]
released in 1.1.0

**Comment by martiesim** [comment]
Thank you very much :)
